// ─── DATA ──────────────────────────────────────────────────────────────────
      const hotels = [
        {
          id: 1,
          name: "Sofitel Legend Metropole",
          stars: 5,
          type: "luxury",
          location: "15 Ngô Quyền, Hoàn Kiếm, Hà Nội",
          price: "3.850.000",
          rating: "9.6",
          reviews: 2847,
          img: "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=700&q=85",
          amenities: ["Hồ bơi", "Spa", "Nhà hàng", "Bar", "WiFi"],
          badge: "Biểu tượng",
        },
        {
          id: 2,
          name: "JW Marriott Hanoi",
          stars: 5,
          type: "luxury",
          location: "8 Đỗ Đức Dục, Mỹ Đình, Nam Từ Liêm, Hà Nội",
          price: "2.950.000",
          rating: "9.4",
          reviews: 1923,
          img: "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=700&q=85",
          amenities: ["Hồ bơi", "Gym", "Spa", "Lounge"],
          badge: "5 sao",
        },
        {
          id: 3,
          name: "La Siesta Premium Hang Be",
          stars: 4,
          type: "boutique",
          location: "94 Hàng Bè, Hoàn Kiếm, Hà Nội",
          price: "1.250.000",
          rating: "9.2",
          reviews: 1456,
          img: "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=700&q=85",
          amenities: ["Rooftop Bar", "WiFi", "Bữa sáng"],
          badge: "Boutique",
        },
        {
          id: 4,
          name: "InterContinental Westlake",
          stars: 5,
          type: "lake",
          location: "5 Từ Hoa, Tây Hồ, Hà Nội",
          price: "3.200.000",
          rating: "9.5",
          reviews: 2134,
          img: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=700&q=85",
          amenities: ["View Hồ Tây", "Hồ bơi vô cực", "Spa", "Fine Dining"],
          badge: "View đẹp",
        },
        {
          id: 5,
          name: "Hanoi La Castela Hotel",
          stars: 3,
          type: "budget",
          location: "56 Hàng Gai, Hoàn Kiếm, Hà Nội",
          price: "680.000",
          rating: "8.8",
          reviews: 987,
          img: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=700&q=85",
          amenities: ["WiFi", "Bữa sáng", "Lễ tân 24h"],
          badge: "Giá tốt",
        },
        {
          id: 6,
          name: "Essence Palace Hotel",
          stars: 4,
          type: "oldquarter",
          location: "22 Tạ Hiện, Hoàn Kiếm, Hà Nội",
          price: "1.450.000",
          rating: "9.0",
          reviews: 1678,
          img: "https://images.unsplash.com/photo-1551882547-ff40c4c97f7b?w=700&q=85",
          amenities: ["Trung tâm phố cổ", "Rooftop", "Bữa sáng", "Spa"],
          badge: "Phố cổ",
        },
        {
          id: 7,
          name: "Lotte Hotel Hanoi",
          stars: 5,
          type: "luxury",
          location: "54 Liễu Giai, Ba Đình, Hà Nội",
          price: "2.750.000",
          rating: "9.3",
          reviews: 1789,
          img: "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=700&q=85",
          amenities: ["Sky Bar", "Hồ bơi", "Spa", "Gym", "Nhà hàng"],
          badge: "Sky lounge",
        },
        {
          id: 8,
          name: "Pan Pacific Hanoi",
          stars: 5,
          type: "lake",
          location: "1 Thanh Niên, Tây Hồ, Hà Nội",
          price: "2.400.000",
          rating: "9.1",
          reviews: 1345,
          img: "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=700&q=85",
          amenities: ["View hồ", "Hồ bơi", "Spa", "Bar"],
          badge: "Hồ Tây",
        },
      ];

      let currentUser = null;
